const cardsList = [
  {
    id: 1,
    topic: "Web Design",
    themeClass: "_orange",
    title: "Название задачи 1",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 2,
    topic: "Research",
    themeClass: "_green",
    title: "Название задачи 2",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 3,
    topic: "Web Design",
    title: "Название задачи 3",
    themeClass: "_orange",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 4,
    topic: "Copywriting",
    title: "Название задачи 4",
    themeClass: "_purple",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 5,
    topic: "Web Design",
    title: "Название задачи 5",
    themeClass: "_orange",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    id: 6,
    topic: "Research",
    title: "Название задачи 6",
    themeClass: "_green",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    id: 7,
    topic: "Research",
    themeClass: "_green",
    title: "Название задачи 7",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 8,
    topic: "Copywriting",
    themeClass: "_purple",
    title: "Название задачи 8",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 9,
    topic: "Web Design",
    themeClass: "_orange",
    title: "Название задачи 9",
    date: "30.10.23",
    status: "В работе",
  },
  {
    id: 10,
    topic: "Research",
    themeClass: "_green",
    title: "Название задачи 10",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    id: 11,
    topic: "Research",
    themeClass: "_green",
    title: "Название задачи 11",
    date: "30.10.23",
    status: "Готово",
  },
];

export default cardsList;
